language: python
matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
  - python: "2.6"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install ."
  - "pip install -r requirements_dev.txt"
script: py.test --cov haralyzer tests/
after_success:
  - coveralls
